baseURL = ""
languageCode = "en-us"
title = "Lucas Zapico Developer Portfolio"
theme = 'luc-v1'
summaryLength = 40
enableRobotsTXT = "True"
enableEmoji = "True"
# set up
googleAnalytics = ""



[params]
    author = "Lucas "
    description = "Dev Portfolio for Lucas Zapico"
    githubUsername = "LucasZapico"
    favicon = "img/favicon-32x32.ico"
    images = ["https://dev.lucaszapico.space/img/site-feature-image.png"]
    alt = "amazing image of dev.lucas website"
    title = "Dev.Lucas"


[taxonomies]
  tag = "tags"
  category = "categories"


[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[test]
  test1 = "bang"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 2


[social]
  # custom
  twitterusername       = "https://twitter.com/lucaszapico10"
  githubusername        = "LucasZapico"
  githublink            = "https://github.com/LucasZapico"
  facebooklink          = "https://www.facebook.com/lucas.zapico.7"
  linkedinlink          = "https://www.linkedin.com/in/lucasmmzapico/"
  pinterestlink         = ""
  codepenlink           = "https://codepen.io/LucasZapico"
  codesandboxlink       = "https://codesandbox.io/u/LucasZapico"
  codewarslink          = "https://www.codewars.com/users/LucasZapico"
  instagramlink         = "https://www.instagram.com/10zapico/"
  # Coding Communities
  github                = ""
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedincompany      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  # Email
  email                 = ""


[sociallinks]
